name: Regenerate Code

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Publish

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://npm.pkg.github.com"

      - name: Install Dependencies
        run: yarn

      - name: Cleanup Old Files
        run: yarn lib:clean

      - name: Generate Code
        run: yarn lib:generate

      - name: Install Library Dependencies
        run: yarn lib:install

      - name: Build Library
        run: yarn lib:build

      # - name: Publish Package
      #   run: yarn lib:publish

      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Regenerate files
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          delete-branch: true
          title: 'Regenerate API'
          draft: false
