name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      
      - name: Install Dependencies
        run: yarn

      - name: Cleanup Old Files
        run: yarn lib:clean

      - name: Generate Code
        run: yarn lib:generate

      - name: Install Library Dependencies
        run: yarn lib:install

      - name: Build Library
        run: yarn lib:build

      - name: Publish Package
        run: yarn lib:publish

        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    